### ISSUE TITLE
Toggle/collapse/put in a tab the instructions screeen

### ISSUE THREAD

**Issue by peter-lyons-kehl** [lukaslueg/macro_railroad#26]
Currently the instructions/docs/reference screen on the right takes half of horizontal dimension, and macro input has only 50% left. Please consider a toggle/collapse/tab for the instructions area.

A workaround in Firefox:
- install [addons.mozilla.org/en-US/firefox/addon/styl-us](https://addons.mozilla.org/en-US/firefox/addon/styl-us)
- in Stylus, enter a style:
```css
/* ==UserStyle==
@name           lukaslueg.github.io - 2022-05-20, 10:46:44 a.m.
@namespace      github.com/openstyles/stylus
@version        1.0.0
@description    A new userstyle
@author         Me
==/UserStyle== */

@-moz-document url-prefix("https://lukaslueg.github.io/macro_railroad_wasm_demo/") {
    div#copytext {
        display: none !important;
    }
    div#content {
        grid-template-columns: 1fr 0fr !important;
    }
}
```
See also lukaslueg/railroad#3.
